sudo: required

services:
- docker

env:
  global:
  - secure: bjtbKM1e2fag1oaabgdQs4QoiJIrUVM2qzmT+Uwypj4zoVikDQHn0aYn9XCL7lBSSVePJ/GdchLTEU9H58G76JXMviN1SXMkbMlZcN6B5lRElFayLxG/Yxnb758OvS/x554paNbkCljuMkYYGriMKjW4C18p8v3YoCANLM4nts5XqT2rqGHVzYqK4q0dLipHWFyjSB7XvJArOH18KD3ry+kaNw4kxo+HexpyDxDDVw+M4xLeNVkp85gSgi8H3JDcHfzNMbGms/gc4liYHcIQt8xhjHPcnOMeYVwk2blUSo+9bgdQZ9z0C2pBno/jSm/w1NmLyZA+iliYTZUlyp8uHh20m3JSB22H13tNt7EMZXWbqt6sDmTEFCLq93ztIw10nWnJkibGj2uj1f8IzCTo0Z9t2QWLdOcpPwZLG3+FuMLF2+nDrnm844DIU7oo3tMudbB7qabcMHunfCGowefCL5H7LKhzG8O/34qSavAJcMhCHsLGXOLch3C/OHmz6GspruMl4bA1DC/3W937Mef2MJVO4XBr5EJpfSIrUyE44kxN7Ebhcb9zesDat7f7dWA3sfKZrJT/AHt1or/wYktLnNcTJjs53Bzp9e0iyIhjSvx4bN/mbi+OIWNVPS4CQ4qcVLYpZROMrY4qL1zbVrGYE7WBwMYpIhoQKvYoa2JAGeM=
  - secure: qmQmGYRFymDkJjbYcnltokuJuNgGICJbPiM7+x3H/f+jfpRFO2JrHCq56ZR4mjph+9tDFlZkg72bVHQvLy8wM/d6gheWfqLc6ysACebs3SuVCfODvOpAy4Am8Fz50XDB2UJELj1xemLkXM8toL3GQVGCBrnk8kWgFJdMfkdUw8gkM938WlwhF+uvsZYfJvxDX60TAi0wzF1Ke3yTnzOT5WZHvKVeMq6WXfoQWvaROzySHjD1MOYI9T2AzqjTK2hvaOuCT3I8bF0hY8U/VIp+qs6ZQSZrMkhhSoT2DIMGD9BezCGF52BN17wDOSFEHPULihEFGNqb0/K9X4KX4nGBXWP4hZC/8DVMyVd4+FXzDLVsqPsdqyWHPYq1Cu3RHnDKoj01OmUkP+jS+Y5cn1Cf0hhwWLwLHULFLQE+Kyhc/S3+bKk16XgFGy4fmYweCuG+q8cVmB63I1wF8FSWjCGHin8l92z6TALxK0o7SUtJWdkXVbJyN4Q+tKcE8D9SXrDkYOmgH33UQnhSnZbN2p2bZn5wvQ1Ou7TK0N8gsjbU4USdM0Gc4LJtFeoO8lFP12ElFX4x3QINWbH9ZKu//w05mof2B+lfSQVxbAepw7n4kvZTj8hZ3zQa/bML9oX0sfK61ITFmbgQkSMXIhwLy8clBW+5C7qghKWhXizbEFKd1Vk=

script:
- echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
- docker build --quiet -t kr7ysztof/keycloak-it:$TRAVIS_BRANCH .;
- docker pull kr7ysztof/keycloak-it:latest;
  docker push kr7ysztof/keycloak-it:$TRAVIS_BRANCH;
  if [ "${TRAVIS_BRANCH}" == "master" ]; then docker tag kr7ysztof/keycloak-it:$TRAVIS_BRANCH kr7ysztof/keycloak-it:latest; docker push kr7ysztof/keycloak-it:latest; fi 